apiVersion: v1
kind: Service
metadata:
  name: demoapp 
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demoapp
